/**
 * Writes the scheme, role, and ability catalogs into docs/DECISIONS.md between the catalog markers, so
 * the decision record always matches the code. A unit test fails when they drift; rerun
 * `npx tsx tools/catalog-doc.ts` after changing a catalog.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { ABILITY_LIST } from '../src/engine/abilities/catalog';
import { COACH_ABILITIES } from '../src/engine/abilities/coaches';
import { RATING_LABELS, type RatingKey } from '../src/engine/model/ratings';
import { STAFF_ROLE_LABELS } from '../src/engine/model/staff';
import { DEFENSE_LIST, OFFENSE_LIST, SPECIAL_ROLES } from '../src/engine/schemes/catalog';
import { ROLES, ROLE_IDS } from '../src/engine/schemes/roles';
import { TRIGGER_LABELS } from '../src/engine/schemes/situations';
import { DEFENSE_SLOTS, OFFENSE_SLOTS } from '../src/engine/schemes/slots';
import {
  DOWN_DISTANCES,
  PERSONNEL,
  RUN_CONCEPTS,
  SHELLS,
  TARGET_SLOTS
} from '../src/engine/schemes/tendencies';

export const START = '<!-- catalog:start (generated by tools/catalog-doc.ts; do not edit by hand) -->';
export const END = '<!-- catalog:end -->';
const FILE = 'docs/DECISIONS.md';

const pct = (v: number): string => `${Math.round(v * 100)}%`;
const num = (v: number): string => (Number.isInteger(v) ? String(v) : v.toFixed(2).replace(/0+$/, ''));
const row = (cells: readonly (string | number)[]): string => `| ${cells.join(' | ')} |`;
const table = (head: readonly string[], rows: readonly (readonly (string | number)[])[]): string =>
  [row(head), row(head.map(() => '---')), ...rows.map(row)].join('\n');

const weights = (w: Partial<Record<RatingKey, number>>): string =>
  (Object.entries(w) as [RatingKey, number][])
    .sort((a, b) => b[1] - a[1])
    .map(([k, v]) => `${RATING_LABELS[k].toLowerCase()} ${num(v * 100)}`)
    .join(', ');

function offenseTables(): string {
  const names = OFFENSE_LIST.map(s => s.name);
  const t = OFFENSE_LIST.map(s => s.tendencies);
  const DD: Record<string, string> = {
    first: '1st down',
    secondShort: '2nd and short',
    secondLong: '2nd and long',
    thirdShort: '3rd and short',
    thirdLong: '3rd and long'
  };
  const rows: (string | number)[][] = [
    ...DOWN_DISTANCES.map(dd => [`Pass rate, ${DD[dd]}`, ...t.map(x => pct(x.passRate[dd]))]),
    ['Average depth of target (yards)', ...t.map(x => num(x.airYards))],
    ['Play action (of dropbacks)', ...t.map(x => pct(x.playAction))],
    ['RPO (of plays)', ...t.map(x => pct(x.rpo))],
    ['Screens (of passes)', ...t.map(x => pct(x.screen))],
    ['Designed QB runs (of runs)', ...t.map(x => pct(x.qbRuns))],
    ['Scramble tolerance', ...t.map(x => num(x.scramble))],
    ['Tempo', ...t.map(x => num(x.tempo))],
    ...PERSONNEL.map(p => [`Personnel ${p}`, ...t.map(x => pct(x.personnel[p]))]),
    ...RUN_CONCEPTS.map(c => [`Run concept: ${c}`, ...t.map(x => pct(x.runConcepts[c]))]),
    ...TARGET_SLOTS.map(s => [`Target share: ${s}`, ...t.map(x => pct(x.targets[s]))]),
    ['Deep shots (of passes)', ...t.map(x => pct(x.deepShots))],
    ['Fourth-down aggressiveness', ...t.map(x => num(x.fourthDown))]
  ];
  const roles = OFFENSE_SLOTS.map(slot => [slot, ...OFFENSE_LIST.map(s => ROLES[s.roles[slot]].label)]);
  return [
    '#### Offensive tendencies',
    table(['Slider', ...names], rows),
    '#### Offensive roles by slot',
    table(['Slot', ...names], roles)
  ].join('\n\n');
}

function defenseTables(): string {
  const names = DEFENSE_LIST.map(s => s.name);
  const t = DEFENSE_LIST.map(s => s.tendencies);
  const rows: (string | number)[][] = [
    ['Front', ...t.map(x => `${x.front}-man`)],
    ['Base package', ...t.map(x => pct(x.packages.base))],
    ['Nickel', ...t.map(x => pct(x.packages.nickel))],
    ['Dime', ...t.map(x => pct(x.packages.dime))],
    ['Blitz (of passes)', ...t.map(x => pct(x.blitz))],
    ['Simulated pressure', ...t.map(x => pct(x.simPressure))],
    ['Man coverage', ...t.map(x => pct(x.man))],
    ...SHELLS.map(sh => [`Shell: ${sh}`, ...t.map(x => pct(x.shells[sh]))]),
    ['Press rate', ...t.map(x => pct(x.press))],
    ['Run fits (0 gap control, 1 penetration)', ...t.map(x => num(x.runFit))],
    ['Stunts and twists', ...t.map(x => pct(x.stunts))]
  ];
  const roles = DEFENSE_SLOTS.map(slot => [slot, ...DEFENSE_LIST.map(s => ROLES[s.roles[slot]].label)]);
  return [
    '#### Defensive tendencies',
    table(['Slider', ...names], rows),
    '#### Defensive roles by slot',
    table(['Slot', ...names], roles)
  ].join('\n\n');
}

function recipeTable(): string {
  const rows = ROLE_IDS.map(id => {
    const r = ROLES[id];
    const traits = r.traits.map(t => `${t.label} ${t.points > 0 ? '+' : ''}${t.points}`).join(', ') || 'none';
    return [r.label, r.primary, weights(r.weights), traits];
  });
  const special = Object.entries(SPECIAL_ROLES)
    .map(([slot, id]) => `${slot} ${ROLES[id].label.toLowerCase()}`)
    .join(', ');
  return [
    '#### Role recipes',
    `Weights are percentages of the role's weighted average; trait points add to the role rating. Special teams roles are the same in every scheme: ${special}.`,
    table(['Role', 'Primary', 'Rating weights', 'Trait adjustments'], rows)
  ].join('\n\n');
}

function abilityTable(): string {
  const rows = ABILITY_LIST.map(a => {
    const when = a.triggers.map(t => TRIGGER_LABELS[t]).join(' or ');
    const contexts = a.contexts?.length ? `, ${a.contexts.map(c => TRIGGER_LABELS[c]).join(' or ')}` : '';
    const boosts = (Object.entries(a.boosts) as [RatingKey, number][])
      .map(([k, v]) => `${RATING_LABELS[k].toLowerCase()} +${v}`)
      .join(', ');
    const needs = (Object.entries(a.requires) as [RatingKey, number][])
      .map(([k, v]) => `${RATING_LABELS[k].toLowerCase()} ${v}`)
      .join(', ');
    return [a.name, a.positions.join(', '), a.tier, `${when}${contexts}`, boosts, needs];
  });
  return table(['Ability', 'Positions', 'Tier', 'Triggers', 'Effect', 'Generated players need'], rows);
}

function coachTable(): string {
  const rows = COACH_ABILITIES.map(a => {
    const effects = [
      ...(a.triggers ?? []).map(t => `${t.side} ${TRIGGER_LABELS[t.trigger]} x${t.multiplier}`),
      ...(a.traits ?? []).map(t => `${t.label} +${t.points}`),
      ...(a.development
        ? [`${a.development.positions.join(', ')} progression +${a.development.points} (M10)`]
        : [])
    ].join('; ');
    return [a.name, a.roles.map(r => STAFF_ROLE_LABELS[r]).join(', '), effects];
  });
  return table(['Coach ability', 'Held by', 'Effect'], rows);
}

export function renderCatalog(): string {
  return [
    START,
    '',
    '### Scheme definitions (D-5)',
    '',
    offenseTables(),
    '',
    defenseTables(),
    '',
    recipeTable(),
    '',
    '### Ability catalog (D-6)',
    '',
    abilityTable(),
    '',
    '### Coach abilities (D-6)',
    '',
    coachTable(),
    '',
    END
  ].join('\n');
}

/** The decisions file with its catalog section replaced (or appended when missing). */
export function withCatalog(text: string): string {
  const block = renderCatalog();
  const start = text.indexOf(START);
  const end = text.indexOf(END);
  if (start === -1 || end === -1) return `${text.trimEnd()}\n\n${block}\n`;
  return `${text.slice(0, start)}${block}${text.slice(end + END.length)}`;
}

if (process.argv[1]?.endsWith('catalog-doc.ts')) {
  writeFileSync(FILE, withCatalog(readFileSync(FILE, 'utf8')));
  console.log(`Wrote the catalogs to ${FILE}`);
}
